/*
 * This source file was generated by the Gradle 'init' task
 */

import spock.lang.Specification
import org.example.App

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.getGreeting()

        then:
        result == "Hello World!"
    }
}
